GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/61441f27f346060e95cd7a2e

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Yanli Pei",
  "subscribedToChannel": "Web Dev Simplified"
}

###
DELETE http://localhost:3000/subscribers/61441f27f346060e95cd7a2e

###
PATCH http://localhost:3000/subscribers/61441f27f346060e95cd7a2e
Content-Type: application/json

{
  "name": "Jiacheng Wang"
}